### ISSUE TITLE
ModEM_plot_depth_slice

### ISSUE THREAD

**Issue by alkirkby** [GeoscienceAustralia/mtpy2#14]
mtpy.imaging.modem_plot_vertical_slice.py is now working for me.
To update:
- Could you please make the tick markers and borders of the plot more similar to the DepthSlice plots?
- Font size, should be an optional argument, I'd like the default text size somewhere between the current size and that in the DepthSlice plot
- datafn and iterfn will need to be optional arguments. Could you make it such that they are optional command line arguments? For the default for iterfn, could do a search for all files ending in .rho and take the latest one (i.e. the one with the highest numbers in the last 3 numbers before .rho). for the data file, the default can be ModEM_data.dat.
- slice_location, stationdist, and zlim will need to be optional arguments as will colormap (currently hardcoded when calling pcolormesh function).
- could we plot the stations as upside down triangles and add option to plot station labels?
- Finally, it'd be good to have optional arguments xpad and ypad, which define how much of the model to show (currently the model  is plotted to the start of the padding cells, we'd need an option to show some of the padding too.
Hope this all makes sense, please ask me if not!

**Comment by zhang01GA** [comment]
ModEM_Data.dat cannot plot.
ModEM_Data_noise10inv.dat  is OK.

u25656@PC-62907 MINGW64 /e/Githubz/mtpy2 (develop)
$ python mtpy/imaging/modem_plot_vertical_slice.py examples/data/ModEM_files/VicSynthetic07/ModEM_Data.dat examples/data/ModEM_files/VicSynthetic07/Modular_MPI_NLCG_019.rho
If you want to write a vtk file for 3d viewing, you need download and install evtk from https://bitbucket.org/pauloh/pyevtk
Note: if you are using Windows you should build evtk first witheither MinGW or cygwin using the command:
    python setup.py build -compiler=mingw32  or
    python setup.py build -compiler=cygwin
If you want to write a vtk file for 3d viewing, you need download and install evtk from https://bitbucket.org/pauloh/pyevtk
Note: if you are using Windows you should build evtk first witheither MinGW or cygwin using the command:
    python setup.py build -compiler=mingw32  or
    python setup.py build -compiler=cygwin
Set rotation angle to 0.0 deg clockwise from N
Traceback (most recent call last):
  File "mtpy/imaging/modem_plot_vertical_slice.py", line 182, in <module>
    myObj=ModemPlotVerticalSlice(datf, rhof)
  File "mtpy/imaging/modem_plot_vertical_slice.py", line 48, in __init__
    self._read_data()
  File "mtpy/imaging/modem_plot_vertical_slice.py", line 55, in _read_data
    self.datObj.read_data_file(data_fn=self.datfile)
  File "E:\Githubz\mtpy2\mtpy\modeling\modem_new.py", line 1344, in read_data_file
    self.mt_dict[s_key].zinv.compute_invariants()
  File "E:\Githubz\mtpy2\mtpy\analysis\zinvariants.py", line 190, in compute_invariants
    self._Z.freq[ii])
AttributeError: Zinvariants instance has no attribute '_Z'

**Comment by alkirkby** [comment]
Yes, that is true, in the example data set ModEM_Data.dat will not plot. In this case, ModEM_Data_noise10inv.dat, needs to be specified in the command line arguments.
However, in the general case, ModEM_Data.dat is the default file name for data files and so it is useful for the code to find it automatically rather than specify it each time.
If you like, I can rename ModEM_Data_noise10inv.dat to ModEM_Data.dat and remove the original. This may make it less confusing for running examples.
