### ISSUE TITLE
Anaconda2\lib\site-packages\matplotlib\backends\backend_qt5agg.py TypeError: 'figure' is an unknown keyword argument

### ISSUE THREAD

**Issue by zhang01GA** [GeoscienceAustralia/mtpy2#19]
Traceback (most recent call last):
  File "C:\Git\mtpy2\mtpy\imaging\modem_plot_vertical_slice.py", line 279, in <module>
    super(FigureCanvasQT, self).__init__(figure=figure)
TypeError: 'figure' is an unknown keyword argument
    myObj.make_plot()
  File "C:\Git\mtpy2\mtpy\imaging\modem_plot_vertical_slice.py", line 149, in make_plot
    plt.figure(figsize=self.fig_size)
 File "C:\Anaconda2\lib\site-packages\matplotlib\pyplot.py", line 535, in figure
    **kwargs)
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 223, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\backend_qt5.py", line 239, in __init__

**Comment by zhang01GA** [comment]
user problem solved
